[workspace]
members = ["packages/*"]

[package]
name = "loadgen-dsl"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = "1.0"
serde_yaml = "0.9"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
