[package]
name = "loadgen-dsl-compiler"
version = "0.0.0"
edition = "2021"
authors = ["INFINI Labs <hello@infini.ltd>"]
license = "AGPL-3.0+"

[dependencies]
loadgen-dsl-parser = { path = "../parser" }
serde = "1.0"
serde_yaml = "0.9"
