[package]
name = "loadgen-dsl-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
miette = "5.10"
serde_yaml = "0.9"
thiserror = "1.0"
